#!/bin/bash

SERVER_HOST="localhost"
SERVER_PORT=5000

case "$1" in
    boom)
        curl "http://$SERVER_HOST:$SERVER_PORT/"
    ;;
    motion)
        curl "http://$SERVER_HOST:$SERVER_PORT/motion"
    ;;
    test)
        curl "http://$SERVER_HOST:$SERVER_PORT/test"
    ;;
    clear)
        curl -X DELETE "http://$SERVER_HOST:$SERVER_PORT/firebase_db"
    ;;
esac
